FROM microsoft/windowsservercore as builder

# TODO: Download Graphviz
# TODO: Download PlantUML


FROM openjdk:8u171-jdk-windowsservercore

# FIXME: It is just for test
RUN java -version

# TODO: install Graphviz
# TODO: install PlantUML
